tags = {
    "morbidly_obese",
    "gore",
    "castration",
    "torture",
    "snuff",
    "necrophilia",
    "amputee",
    "rape",
    "explicitly_stated_nonconsent",
    "questionable_consent",
    "urine",
    "watersports",
    "feces",
    "scat",
    "diaper",
    "fart",
    #"young rating:e",
    #"young rating:q solo",
    #"cub -rating:s",
    "cub",
    "shota",
    "loli",
    "human_on_feral",
    "bestiality",
    "incest_(lore)",
    "advertisement",
    "distracting_watermark",
    "nezumi_(artist)",
    "nightmare_fuel",
    "what",
    "flash",
    "huge_filesize",
    "vore",
    "hyper",
    "comic"
}
